import AppKit
import Testing
@testable import apfel_clip

@Suite("PasteboardClipboardService")
@MainActor
struct PasteboardClipboardServiceTests {
    @Test("TransientType clipboard content is ignored for history")
    func transientTypeIsIgnored() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        ]

        #expect(PasteboardClipboardService.shouldIgnoreHistory(for: types))
    }

    @Test("ConcealedType clipboard content is ignored for history")
    func concealedTypeIsIgnored() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        ]

        #expect(PasteboardClipboardService.shouldIgnoreHistory(for: types))
    }

    @Test("AutoGeneratedType clipboard content is ignored for history")
    func autoGeneratedTypeIsIgnored() {
        let types: [NSPasteboard.PasteboardType] = [
            .string,
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        ]

        #expect(PasteboardClipboardService.shouldIgnoreHistory(for: types))
    }

    @Test("Normal text clipboard content is still recorded")
    func normalTextIsNotIgnored() {
        let types: [NSPasteboard.PasteboardType] = [.string]

        #expect(!PasteboardClipboardService.shouldIgnoreHistory(for: types))
    }
}