name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-package:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run tests
        run: swift test

      - name: Build app bundle
        run: ./scripts/build-app.sh
